version: '2'

volumes:
  mysql-data: {}

networks:
  mynetwork:
    driver: bridge

services:
  nginx:
    build: ./docker/nginx
    ports:
      - 8080:80
      - 443:443
    volumes:
      - .:/var/www/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/
    networks:
      - mynetwork
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: hq
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: hotelquickly
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
      - mynetwork


